### ISSUE TITLE
Create debug server

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/horcrux#104]
In order to wire in the prometheus metrics #93, we need a debug server so that we can have a single listen address for multiple concerns. The prometheus handler can be included in the mux at the `/metrics` endpoint.

Here is the implementation in the relayer for reference:
https://github.com/cosmos/relayer/blob/main/internal/relaydebug/debugserver.go

Suggestion by @mark-rushakoff :
> It will probably be a copy and paste today, but if we do this on a third utility, then maybe it will be worth extracting a small module to capture all of it

**Comment by chillyvee** [comment]
Added debug server: https://github.com/strangelove-ventures/horcrux/pull/93
