### ISSUE TITLE
Add prometheus to horcrux

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#11]
https://prometheus.io/docs/guides/go-application/

The following are ideas for metrics to be tracked:
- [ ] Missed blocks (i.e. `simd q slashing signing-info`)
- [ ] last blockheight signed
- [ ] average request latency to other signers in the cluster
- [ ] average request latency to any connected sentries
- [ ] total blocks signed
- [ ] time since last signature
- [ ] block height of attached nodes
- [ ] p2p metrics, any and all about the signer p2p layer
- [ ] connection status for sentries
- [ ] p50, p95, p99 signing latency for the cluster

**Comment by Stakecraft** [comment]
maybe would be useful to have as well:

- [ ] raft leader
- [ ] signer cluster status

**Comment by PFC-developer** [comment]
Any chance you could show 95th percentile when it comes to latency.
For the one doing the signing, maybe which others contributed..
I'd be curious to see if it was always the same nodes contributing vs all of them doing it equally.

**Comment by agouin** [comment]
Closed by #93
