### ISSUE TITLE
Unable to get metrics working

### ISSUE THREAD

**Issue by echel0n** [strangelove-ventures/horcrux#116]
I've tried what was suggested in the metrics document to add `debug-listen-address: 0.0.0.0:6001` to config and this does not seem to enable metrics, can you please help resolve this.

Thanks!

**Comment by samuel-tay** [comment]
same issue here, both on 2.0.0 and 2.1.0-rc1, logs show that debug address was not set.

**Comment by agouin** [comment]
The config param is `debug-addr`. The debug server was introduced in `v2.1.0-rc1`. The docs mistakenly called the param `debug-listen-address`. Docs updated in #117

**Comment by samuel-tay** [comment]
> 

Thanks, can confirm working now.
