### ISSUE TITLE
[Help Wanted] Setting up Ethereum Bridge Relays (Peggo)

### ISSUE THREAD

**Issue by debjit-bw** [strangelove-ventures/horcrux#120]
For chains which have ethereum brodge relays, like peggo, where do we set that up? things like peggo need to be set up on a validator, but in the horcrux setup the sentries are just fullnodes. so where should we run these relayers like peggo?

**Comment by agouin** [comment]
In the horcrux setup, sentries are more than just fullnodes. They have the priv-val interface enabled to allow connection from the horcrux cosigner(s), send block sign requests over the websocket, and submit the signatures returned from the horcrux cluster to the chain.

The orchestrator process(es) can be configured alongside one or multiple of the sentry nodes.

**Comment by debjit-bw** [comment]
@agouin thanks a lot!
