### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#13]
Currently logging in the signer is quiet and not as informative as it could be. We should utilize the `tendermint` logging library and use their different `log.Info`, `log.Warn`, `log.Error`, and `log.Debug` levels. Debug should be very verbose and allow for diagnostic looks into the logs, Info should contain much of what is currently being logged and error and warn should be used for errors (things that can be safely ignored, Warn, anything requiring more attention, Error)

**Comment by agouin** [comment]
Resolved by #38. All logging now goes through the tendermint logging library, and debug logs have been added to help troubleshoot issues.
