### ISSUE TITLE
Does Horcrux support YubiHSM2?

### ISSUE THREAD

**Issue by Chomtana** [strangelove-ventures/horcrux#145]
Currently, we are using TMKMS with YubiHSM2 as a signer node. Now we would like to expand to more than one signer node to reach high availability. However, we couldn't find any document on using Horcrux together with YubiHSM2.

Does Horcrux support YubiHSM2? If it doesn't, can you suggest any alternatives?

**Comment by agouin** [comment]
Thank you for your question! Horcrux does not currently have an HSM integration, but we are underway on refactors to make it possible in #46
