### ISSUE TITLE
v3 breaks on Ubuntu 20.04

### ISSUE THREAD

**Issue by samuel-tay** [strangelove-ventures/horcrux#154]
Not sure if this is intended, but v3 is built on latest Ubuntu release and so uses the latest GLIBC (2.35) which is not supported by 20.04 (2.31). Might not be supported by other distros as well.

```
./horcrux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./horcrux)
./horcrux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./horcrux)
```

**Comment by jmc000** [comment]
observing the same problem here
