### ISSUE TITLE
Investigate / mitigate Increased latency on v3.0.0

### ISSUE THREAD

**Issue by gle1pn1r** [strangelove-ventures/horcrux#156]
After upgrading to v3.0.0, we see increased latency on the metrics `signer_cosigner_sign_lag_seconds` and `signer_cosigner_ephemeral_share_lag_seconds`. 

The latency increase is around 60% for `signer_cosigner_ephemeral_share_lag_seconds` and 30% for `signer_cosigner_sign_lag_seconds`. In the case of `signer_cosigner_sign_lag_seconds` the latency increase is the same from the local host, i.e. the leader.

We also gather regular ICMP ping latencies between our nodes, and those are stable - no change.

This is on a testnet cluster where cosigners and sentries are all colocated.

The spike/drop in regular latency (right hand column) can be disregard - related to adjusting collector to changes introduced.
 
 
Chain A:
![image](https://github.com/strangelove-ventures/horcrux/assets/102957399/353dd261-90d3-41ca-a340-3239eee9c949)

Chain B (the gap filters out a different leader):
![image](https://github.com/strangelove-ventures/horcrux/assets/102957399/15ad6fc0-332f-4292-9d27-1fc39f1b9155)

The setup is exactly the same - same leaders, no proxying.

**Comment by vimystic** [comment]
Status : Found the root cause . It was GoLang Version change from 1.19 to 1.20.  (PR id : 141)
Applied the fix to branch 156. 

Todo : make the required CI changes on the workflow files and submit a PR.

**Comment by 0xbotchedgarden** [comment]
OK. Unfortunately we shut down the testnet cluster, so don't have the option to test/verify currently. Do you know more specifically what was the root cause?

**Comment by gle1pn1r** [comment]
OK, thank you. We shut down the testnet cluster so can't test/verify currently. Do you know more specifically what was the root cause?

**Comment by jonathanpberger** [comment]
Go latest (1.2.20.6) seems to have solved this.
