### ISSUE TITLE
Version simd containers based on go.mod file

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#17]
See comment: https://github.com/strangelove-ventures/horcrux/blob/8cc8fdd354f86f21a4c7eff8c0f524d392b0782e/.github/workflows/release.yml#L23

Also see `gorelease.yaml` for additional pointers here. 

The above is wrt getting CI to produce the containers automatically. This version will need to be pulled from the go mod file when running the tests. Either the `runtime` package or the `mod` package from the stdlib should get us there.

**Comment by agouin** [comment]
Resolved by #38
