### ISSUE TITLE
Run without chainNodes/privValAddr

### ISSUE THREAD

**Issue by activenodes** [strangelove-ventures/horcrux#191]
@agouin thank you for this explanation [https://github.com/strangelove-ventures/horcrux/issues/100](url)

What do you think of this "hybrid" setup ?

2 Datacenter (with in each: 1 sentry and 1 signer)
1 Spare Datacenter (with 1 signer and without sentry)

```
DC01
Sentry01 <-> Signer01 <->|to S. 2+3

DC02
Sentry02 <-> Signer02 <->|to S. 1+3

DC03
             Signer03 <->|to S. 1+2
```

this way each sentry is connected to its own local signer (latency 0) and there is an additional signer reachable p2p by the other signers when a DC is down.

I think it's the minimum configuration, but with high performance and full redundancy.

Signers connected to all sentries may cause connections cross like `Sentry01<->Signer02` and `Sentry02<->Signer01`. Right?

So in the Signer03 we need to run without "chainNodes/privValAddr" but the result is:

`Error: need to have chainNodes configured for priv-val connection`

**Comment by activenodes** [comment]
Otherwise we could make this dynamic:
https://github.com/strangelove-ventures/horcrux/blob/03f565d67bb5394a4b3017a1adb00561d5297724/signer/remote_signer.go#L21

and insert a dummy IP.

Example:
```
chainNodes:
- privValAddr: tcp://127.0.0.1:1234
  connRetrySec: 99999
```

**Comment by agouin** [comment]
This would be a nice feature. We will get this in the next release

**Comment by activenodes** [comment]
> This would be a nice feature. We will get this in the next release

Thank you! 
I'm migrating from some TMKMS clusters to Horcrux, testing it in every way... great development

**Comment by activenodes** [comment]
@agouin please remember this 🙏
