### ISSUE TITLE
Add procedure in documentation on how to change IP to peers

### ISSUE THREAD

**Issue by AlessandroPaparella** [strangelove-ventures/horcrux#195]
Documentation lack of clear info on how to migrate a peer on a new IP, could you add the necessary steps?
Or in alternative add a new command in horcrux binary to quickly perform this operation?

Thanks.

**Comment by agouin** [comment]
To change the DNS/IP of a cosigner:
- update config files on each cosigner
- bring all cosigners down
- remove the `.horcrux/raft` directory on all cosigners
- restart all cosigners

**Comment by akc2267** [comment]
https://github.com/strangelove-ventures/horcrux/pull/213
