### ISSUE TITLE
horcrux should have a CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by beckettsean** [strangelove-ventures/horcrux#199]
Examples to synthesize:

https://github.com/cosmos/interchain-security/blob/main/CONTRIBUTING.md
https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md
https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md
https://github.com/cosmos/ibc-rs/blob/main/CONTRIBUTING.md
https://github.com/strangelove-ventures/cosmos-operator/blob/main/docs/contributing.md

**Comment by beckettsean** [comment]
related to https://github.com/strangelove-ventures/interchaintest/issues/776

**Comment by akc2267** [comment]
We should be able to copy this over from interchaintest (thanks @Reecepbcups!)

**Comment by akc2267** [comment]
will be closed with https://github.com/strangelove-ventures/horcrux/pull/208
