### ISSUE TITLE
feature request: metrics should have 'chain-id' where feasible

### ISSUE THREAD

**Issue by PFC-developer** [strangelove-ventures/horcrux#204]
in my configuration I have multiple horcrux services running (I deploy 1 horcrux service for each chain, not 1 horcrux service for ALL chains).

it would be nice to be able to specify a 'chain_id' or some custom label similar to how cosmos does.

for example:
```
global-labels = [
["chain_id","migaloo-1"],
]
```
it also looks like horcrux creates metrics with the hostname embedded into them.
for example
```
horcrux_andromeda_horcrux_0_runtime_alloc_bytes
```
shouldn't it just do 
horcrux_runtime_alloc_bytes ?

**Comment by agouin** [comment]
Resolved by #198 #219
