### ISSUE TITLE
Signers report signing block but in reality block had not been signed 

### ISSUE THREAD

**Issue by msobh13** [strangelove-ventures/horcrux#217]
I am using horcrux with testnet namada in signing cluser ( 3 signers and 1 node ) it was 2 nodes before but i changed to 1 node just for better troubleshoot . 

as you can see from the attached iamges . the signers reporting success signing blocks > ex in this case block #127920 but in reality 127920 block had not been signed . first image was taking directly by curling the blockchain db to check the signing on the blocks

So how to fix this or what could i do to better debug this .

Node its self is a vlaidator and it sign blocks from time to time using same exat setup . even when it stopped signing blocks it resume on its own . 

ping time between signers are 30-50ms max . and between signers and node 80ms max . 

horcrux version is 3.1.0

<img width="593" alt="namada01" src="https://github.com/strangelove-ventures/horcrux/assets/78115394/594b37ae-9713-4ebb-9ffb-08503ce03004">
<img width="1042" alt="namada3" src="https://github.com/strangelove-ventures/horcrux/assets/78115394/e7f06da7-9189-47bd-b90d-c9a331159927">
<img width="964" alt="namada5" src="https://github.com/strangelove-ventures/horcrux/assets/78115394/c895d671-cfce-4d52-a92b-5f87751a5a52">
<img width="955" alt="nmada2" src="https://github.com/strangelove-ventures/horcrux/assets/78115394/6a9aa9d9-389a-4802-99d1-b08996a49e3f">

**Comment by agouin** [comment]
Please see my response here https://github.com/strangelove-ventures/horcrux/issues/214#issuecomment-1789532224 for more context on the network round trips required for signing a block. 

From your leader cosigner logs, horcrux did not sign a prevote for 127920, only the precommit, which would cause a block miss. Also, horcrux could sign a block successfully but the signature could still not get back to the rest of the validators within the timeout period, so network latencies are important.

I would check what your ping is to the other validators in the set, especially those with the highest voting power. Those pings within your own validator's network are a bit high, but should be fine for signing ~5 second blocks.

**Comment by msobh13** [comment]
Thanks for reply . i have only 1 validator and the ping between any of these servers is less than 90ms max . most of the time it is 40ms. and when these issue happen chain was producing 2 blocks per minute which is not that fast. i have other chain prodcuing 1 block every 3 seconds and it is working fine

**Comment by msobh13** [comment]
Ok I will try one more time with new setup in same DC to see if that will make any difference . Will update this later . Thanks
