### ISSUE TITLE
Horcrux should support `bn254` key type.

### ISSUE THREAD

**Issue by dylanschultzie** [strangelove-ventures/horcrux#225]
As SL
We want Union to be able to use Horcrux
Because we care about them

[Union](https://union.build/) will require a new key type, `bn254`, rather than the tried-and-true `ed25519` key. Here in their docs is the example:

https://docs.union.build/infrastructure/node_operators/getting-started#initialization

At the moment is appears you can manually change the key type to `ed25519`, but that appears to not be the recommended course of action.

With the importance of `Union` joining the cosmos, it seems worthwhile to support their preferred key scheme.

**Comment by nitronit** [comment]
I think the work needed is slightly larger than just change the key type in Horcrux.  You need to implement the curve.

With that said it is possible to implement the bn254 curve in Horcrux.

As a reference see:
https://github.com/IBM/TSS for a implementation of a threshold BLS using bn254 from Gnark-crypto
https://asecuritysite.com/bn/bn254
https://github.com/Consensys/gnark-crypto

**Comment by danbryan** [comment]
@agouin any update on this?

**Comment by jonathanpberger** [comment]
@agouin told @danbryan we don't need to track this story in this backlog. Closing ticket.
