### ISSUE TITLE
config file for multiple chains 

### ISSUE THREAD

**Issue by HikaruG** [strangelove-ventures/horcrux#269]
# Question
I would like to know how I should add chain B to an existing horcrux cluster for chain A. 

## Context

Current config for chain A's horcrux 3-2 setup:  
```bash
signMode: threshold
thresholdMode:
  threshold: 2
  cosigners:
  - shardID: 1
    p2pAddr: tcp://172.31.0.X:2222
  - shardID: 2
    p2pAddr: tcp://172.31.0.Y:2222
  - shardID: 3
    p2pAddr: tcp://172.31.0.X:2222
  grpcTimeout: 1000ms
  raftTimeout: 1000ms
chainNodes:
- privValAddr: tcp://<public-ip1>:1234
- privValAddr: tcp://<public-ip2>:1234
debugAddr: ""
grpcAddr: ""
``` 

I would like to use the same signers X,Y,Z which would connect to chain B's fullnodes `public-ip3` and `public-ip4`
From v3 docs it seems feasible as you can create sharded-keys for different chains, but I couldn't find information as to how to modify the config file.   

Any help would be greatly appreciated!

**Comment by agouin** [comment]
You can simply add the additional chain sentries to the `chainNodes` section. Horcrux determines the chain ID from the sign requests that come from the sentries to know which shard to sign with.
