### ISSUE TITLE
Does Horcrux support Secp256k1 Encryption?

### ISSUE THREAD

**Issue by roomit-xyz** [strangelove-ventures/horcrux#272]
Hallo Team,

Does Horcrux support Secp256k1 Encryption?

Best Regards
Dwi

**Comment by agouin** [comment]
It does not support secp256k1 and this is not planned as a feature currently. Can you explain your use-case?

**Comment by manueldalb2** [comment]
> It does not support secp256k1 and this is not planned as a feature currently. Can you explain your use-case?

Story is actually using tendermint/PubKeySecp256k1 for pub_key

**Comment by kinrokinro** [comment]
Story +

**Comment by BrainCord** [comment]
Story +

Reference: https://docs.story.foundation/docs/tokenomics-staking

> Validator and delegator public keys are **secp256k1** keys. The keys have a 33 bytes compressed version and 65 bytes uncompressed version. When interacting with the story's smart contracts, a 65 bytes uncompressed key is used to identify validators and delegators. When using story’s staking APIs, the bech32 address that can be derived from the compressed key is used.

**Comment by tiagocmachado** [comment]
Story +
