### ISSUE TITLE
Add test case for downed signer

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#29]
We need to simulate taking down individual nodes in the signer cluster and ensure that the HA is working as intended. Maybe test takes down each signer for a period of time and ensures continued operation

**Comment by mturkia** [comment]
When horcrux traffic is dropped between the cluster nodes, this leads to missing signing. Can be replicated e.g. with_iptables -I INPUT -p tcp --dport <p2p-listen port> -j DROP_
I initially noticed this when rebooting one horcrux node and missing signing during that time.
