### ISSUE TITLE
Horcrux v2 - Raft edition 🛶

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#36]
We are going to implement a raft cluster for leader election. Only the leader will be able to submit signatures to sentries and all nodes will still maintain a high watermark HRS file outside consensus for protection against node take over (i.e. in the case where an attacker gains access to a single node in the cluster the attacker would only be able to cause a service disruption not a double sign event).

We plan to use https://github.com/strangelove-ventures/raft-sample as a basis for the implementation i.e. using [hashicorp/raft](https://github.com/hashicorp/raft) and a database backend ([badgerdb](https://github.com/dgraph-io/badger)?). Data to be stored in consensus:
- High watermark (i.e. what is the latest HRS that the cluster has sent to sentries)
- Sentry nodes
- Cluster members?

**Comment by jackzampolin** [comment]
Unanswered questions for Jack:
- [ ] Service discovery - how do we want the signer nodes to discover each other? Current method (hardcoding the peers in the config file) has some potential downsides but should be fine. Many of the Raft example repos I've seen don't do this.
- [ ] Do we want to store last sign state in consensus and if so where and when do we rely on it?
- [ ] Is there some required user intervention for picking the leader?

**Comment by freshfab** [comment]
Great to see Raft on the roadmap! I have written a [Raft leader election implementation](https://github.com/BlockscapeNetwork/raftify) myself, which I think we could use as a baseline. I've also written a short [Medium article](https://blockscape-network.medium.com/high-availability-for-cosmos-validators-meet-raftify-bdd9f18b9156) about it. It already implements pre-votes (see [chapter 5](https://www.openlife.cc/sites/default/files/php_uploads/4-modifications-for-Raft-consensus.pdf)) and leader stickiness (see [chapter 6](https://www.openlife.cc/sites/default/files/php_uploads/4-modifications-for-Raft-consensus.pdf)), which would be absolutely necessary to guarantee a single leader at all times (=during full and partial network partitions).
