### ISSUE TITLE
Migrate PrivVal from socket to grpc

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#39]
https://github.com/tendermint/tendermint/issues/5883

We have about a year for this but good to get it up in the issues

**Comment by agouin** [comment]
This will be a change in the way tendermint connects to the sentry nodes (introduced in v0.35.0)

One idea is to use horcrux v3.x for the new grpc connection, and remove the socket connection from v3. Then users on chains using tendermint <v0.35.0 could use v2.x, and we could maintain it on a separate branch (e.g. `v2.x` for the 2.x trunk and `main` for the 3.x trunk).

Another idea is to have a config parameter in v3.x to allow using either the socket or the grpc connection. This would mean more permutations in the code but we would only have to maintain one branch, and users could use v3.x for any version of tendermint.

**Comment by akc2267** [comment]
grpc is now in horcrux
