### ISSUE TITLE
[ICS support] Test case and docs should exist for validating multiple networks from one signer cluster.

### ISSUE THREAD

**Issue by jackzampolin** [strangelove-ventures/horcrux#45]
Add test case and docs for validating multiple networks from one signer cluster

**Comment by danbryan** [comment]
@agouin Might want to consider adding support for this too.  Stakers will be able to vote on changing the consensus-key for any given consumer chain.  This is not in the main branch yet, but is in `ghcr.io/strangelove-ventures/heighliner/gaia:goc-dec-7` if you want to dig in.

```
~ $ gaiad tx provider assign-consensus-key
Error: accepts 2 arg(s), received 0
Usage:
  gaiad tx provider assign-consensus-key [consumer-chain-id] [consumer-pubkey] [flags]
```

**Comment by boojamya** [comment]
In progress: https://github.com/strangelove-ventures/horcrux/pull/122
