### ISSUE TITLE
Abstract local cosigner sign methods into interface

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/horcrux#46]
Abstract the local cosigner sign methods into a common interface so that various HSMs can be implemented using the interface
```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/horcrux/pull/98
- [ ] https://github.com/strangelove-ventures/horcrux/pull/160
```

**Comment by boojamya** [comment]
https://github.com/strangelove-ventures/horcrux/pull/67

**Comment by boojamya** [comment]
**WIP**

Phase 1: https://github.com/strangelove-ventures/horcrux/pull/98

**Comment by nitronit** [comment]
Phase 1: https://github.com/strangelove-ventures/horcrux/pull/98 now merged.
