### ISSUE TITLE
Mis-tagging of votes received

### ISSUE THREAD

**Issue by ericjohncarlson** [strangelove-ventures/horcrux#58]
I believe the raft-leader console is mis-representing which nodes have signed.  This is a 3 node config.  I have validated that each of the `private_share_*.json` files are on the correct nodes, and each of those files is called `share.json`.

Config on node 3:
```bash
home-dir: /home/rhino/.horcrux
chain-id: uni-2
cosigner:
  threshold: 2
  shares: 3
  p2p-listen: tcp://0.0.0.0:2222
  raft-listen: 10.254.100.212:2223
  peers:
  - share-id: 1
    p2p-addr: tcp://10.254.100.210:2222
    raft-addr: 10.254.100.210:2223
  - share-id: 2
    p2p-addr: tcp://10.254.100.211:2222
    raft-addr: 10.254.100.211:2223
  rpc-timeout: 1500ms
chain-nodes:
  - priv-val-addr: tcp://10.254.106.191:1234
  - priv-val-addr: tcp://10.254.106.192:1234
  - priv-val-addr: tcp://10.254.106.193:1234
```

When that node is the leader, the console shows:

```bash
D[2022-02-21|09:13:18.778] I am the raft leader. Managing the sign process for this block module=validator
D[2022-02-21|09:13:18.815] Have threshold peers                         module=validator
D[2022-02-21|09:13:18.815] Number of eph parts for peer                 module=validator peer=1 count=1
D[2022-02-21|09:13:18.815] Number of eph parts for peer                 module=validator peer=3 count=1
D[2022-02-21|09:13:18.831] Received signature from 1                    module=validator
D[2022-02-21|09:13:18.834] Received signature from 3                    module=validator
```

The same thing happens for node 2, showing that 1 & 2 have signed.  

The swarm seems to be signing fine, just cosmetic?  The docs are a bit confusing on the naming of the `share.json` files on [migrating.md](https://github.com/strangelove-ventures/horcrux/blob/main/docs/migrating.md).  So I could have an incorrect configuration.

**Comment by agouin** [comment]
The threshold signing process is documented [here](https://github.com/strangelove-ventures/horcrux/blob/main/docs/signing.md#threshold-validator-signing-process). The raft leader will only wait for the `(threshold - 1)` number of peers to respond, designated as `blockSigners` in this doc.

The local cosigner (i.e. the node # of the raft leader) will always be included in the `blockSigners`. If you watch the logs on node 3 for a longer period of time, you should see that both 1 and 2 are being included for different blocks depending on which one responded sooner, unless one of them is always responding sooner.

Let me know what is confusing in the migrating doc for the `share.json` file, but it appears you have it configured correctly. `~/.horcrux/share.json` is the default filename, but it can be overrided with `-k`/`--keyfile` flag (`key-file` property in the generated config).

**Comment by ericjohncarlson** [comment]
Thanks for the quick reply, Andrew.

That makes sense.  It's not that the leader needs to hear from all nodes, it needs two responses and, of course, the leader itself is considered valid as one of those two.   These 3 are across multiple machines in the same co-lo, so I think the fact that the latency is instant, the same secondary signer is active at all time, hence adding to my confusion.

For the docs, the line ` It is very important to make sure the share id (in private_share_*.json as .id)` is confusing.  If you're open for a layman like myself adding some documentation PRs for clarity, I'll do so.

**Comment by agouin** [comment]
That would be great!
