### ISSUE TITLE
state set isRunning check not working for me

### ISSUE THREAD

**Issue by danbryan** [strangelove-ventures/horcrux#79]
This [function](https://github.com/strangelove-ventures/horcrux/blob/93e6b7fc4a43ff495514adee5f26bedd7c2defa7/cmd/horcrux/cmd/state.go#L124) does not appear to be working properly.

![image](https://user-images.githubusercontent.com/807940/175789137-7037a5e7-5429-48a6-9b39-4801e5271536.png)

```
root@ip-10-1-1-10:~# ps -ax |pgrep horcrux
root@ip-10-1-1-10:~# horcrux state set 273596
Error: cannot modify state while horcrux is running
```

**Comment by pratikbin** [comment]
I think `ps -ax | grep horcrux | grep -v grep` will work
